### ISSUE TITLE
Como acompanhar o andamento dos alunos fazendo exercícios?

### ISSUE THREAD

**Issue by huogerac** [devpro-br/lista-de-exercicios-python-brasil#6]
## Problema

Como acompanhar quem está fazendo e em qual parte cada pessoa está de alguma forma? ou seja, no melhor cenário, apenas quando alguem finalizar todos os testes existentes, será o fim! certo?

## Sugestões

Ter um cenário com "milestones" ou agrupar conjuntos de testes por algum período de tempo. Por exemplo, todos os testes da pasta "01_sequencias" ou os 15 primeiros testes estão dentro da milestone "1a semana"
- Talvez desta forma, os interessados por uma "revisão de código" poderiam fazer um PR com os testes passando na primeira parte
- Cada milestone o grupo de testes poderiam estar seguimentados em yaml (do github actions) separados. Exemplo: semana-01-sequencias, semana-02-arrays etc...

**Comment by renzon** [comment]
Como conversamos pessoalmente, estou pensando em definir os Milestone no próprio README, e fazer os milestones de acordo com as seções de exercícios. Assim a pessoa manda PR assim que conseguir fazer passar todos os testes de cada seção, faz sentido? Também gostaria de consolidar esse avanço em termos de datas, potencialmente em outro repo, onde a pessoa colocaria seu nome, a fim de formar uma base de dados e até gamificar a resolução de exercícios e projetos.
